- app/config/ezplatform.yml
> Added default ezplatform.yml file from eZStudioDemoBundle

- INSTALL.md
> EZS-685 : Minor typo in Installation instructions

- app/config/ezplatform.yml
Removes hardcoded StudioDemoBundle layout from Studio UI and makes it configurable
> Studio UI base template in config YML file

- app/config/ezplatform.yml
> Removed extra siteaccesses.

- app/config/ezplatform.yml
> Changed to the way it's done in eZ Platform.

- app/AppKernel.php
- app/config/routing.yml
- composer.json
JIRA: https://jira.ez.no/browse/EZS-1167
> EZS-1167 Add Form Builder component to ezstudio meta repository

- app/AppKernel.php
- app/config/routing.yml
- composer.json
JIRA: https://jira.ez.no/browse/EZS-1169
> EZS-1169 Add Date Based Publisher component to ezstudio meta repository.

- app/AppKernel.php
> Unnecessary backslash

- app/AppKernel.php
**JIRA ticket related**: https://jira.ez.no/browse/EZS-1255
> EZS-1255: CronBundle is missing in AppKernel

- INSTALL.md
Link to the main page and not to a specific version
> Updated link to support portal

- composer.json
https://jira.ez.no/browse/EZS-1271
> EZS-1271: Rename composer packages to be consistent with the new naming

- README.md
> Change Studio to Enterprise in readme

- README.md
> Correct link to jira project

- behat.yml.dist
Jira ticket: EZEE-1485: Move form builder scenario to ezstudio form builder bundle -  https://jira.ez.no/browse/EZEE-1485
This PR is best to be reviewed together with: [form-builder PR](https://github.com/ezsystems/ezstudio-form-builder/pull/146)
Very similar thing has been done recently for date-based-published in [another PR](https://github.com/ezsystems/ezplatform-ee/pull/50)
> EZEE-1485: Update behat.yml.dist file

- composer.json
https://jira.ez.no/browse/EZEE-1444
> EZEE-1444: Store StudioUI 3rd-party dependencies in a separate bundle

- composer.json
Updated composer.json by removing a dependency to `ezsystems/ezplatform-ee-assets`. This is a dependency of `ezsystems/StudioUIBundle`
> EZEE-1444: Updated composer.json

- behat.yml.dist
Jira: https://jira.ez.no/browse/EZEE-1515
Just adding one line to imports for landing page fieldtype.
Required by https://github.com/ezsystems/EzLandingPageFieldTypeBundle/pull/167.
> [Behat] EZEE-1515: Add behat suites line for landing page fieldtype

- behat.yml.dist
Jira: https://jira.ez.no/browse/EZEE-1516
Adding of one line to imports for ezstudio demo bundle.
Required by https://github.com/ezsystems/ezstudio-demo-bundle/pull/186.
> [Behat] EZEE-1516: Add behat suites line for ezstudio demo bundle

- .ez.yml
- behat.yml.dist
- behat_suites.yml
Jira: https://jira.ez.no/browse/EZEE-1526
This is required by https://jira.ez.no/browse/EZEE-1514 because demo meta is a fork. It (1526) can't be finalised now (not before https://jira.ez.no/browse/EZEE-1519 is done) so there's no need to create Jenkins files yet \cc @vidarl .
This PR can be merged into the fork without changing - I will create separate PR in the fork \cc @lserwatka .
> [Behat] EZEE-1526: Cover clean meta repo with scenarios

- .ez.yml
Jira: https://jira.ez.no/browse/EZEE-1526
Removes unnecessary "meta" section from the .ez.yml file.
> [Behat] EZEE-1526: Remove meta section from .ez.yml

- INSTALL.md
- app/config/parameters.yml.dist
Updated naming and links to Confluence.
> EZEE-1489 - install.md update

- behat.yml.dist
JIRA ticket: https://jira.ez.no/browse/EZEE-1517
This should be merged together with: https://github.com/ezsystems/content-on-the-fly-prototype-bundle/pull/35 (adding an empty configuration file to make sure tests in other bundles can pass).
The real configuration is added in https://github.com/ezsystems/content-on-the-fly-prototype-bundle/pull/34 , but it requires this PR to be merged first (to run Ezrobot for that branch).
> EZEE-1517: Add ContentOnTheFly suite

- app/AppKernel.php
- composer.json
Add WhiteOctoberPagerfantaBundle to implement pagination feature in new Admin UI
> Add WhiteOctoberPagerfantaBundle

- app/config/config.yml
- composer.json
**Jira ticket:** https://jira.ez.no/browse/EZP-28434
> EZP-28434 As a developer, I want to compile sass in assetic

- .env
- .ez.yml
- app/AppKernel.php
- composer.json
> JIRA: https://jira.ez.no/browse/EZEE-2007
> EZEE-2007: Rename ezsystems/ezstudio-installer to ezsystems/ezplatform-ee-installer

- behat.yml.dist
Adding page builder tests suite.
> EZP-29108: Adapt behat.yml.dist for PageBuilder

- LICENSE
Similar update will be reflected on ez.no
> Udate to TTL license

- app/AppKernel.php
- app/config/config.yml
- composer.json
> JIRA: https://jira.ez.no/browse/EZEE-2284
Enables https://github.com/Gregwar/CaptchaBundle for the needs of ezsystems/ezplatform-form-builder#39 (EZEE-2284).
> EZEE-2284: As an editor I want to see a preview of a Captcha form field

- behat.yml.dist
[EZEE-1674](https://jira.ez.no/browse/EZEE-1674) Create a spike of Form Builder Behat system test scenarios for v2 - adding FormBuilder behat suites to `behat.yml.dist`.
> EZEE-1674 Create a spike of Form Builder scenarios for v2

- package.json
**Jira ticket:** https://jira.ez.no/browse/EZP-30051
> EZP-30051: Use Webpack Encore in Form Builder bundle

- app/AppKernel.php
- app/config/routing.yml
- composer.json
>JIRA : https://jira.ez.no/browse/EZP-29140
> EZP-29140: User Bundle

- config/routes/ezplatform_form_builder.yaml
>JIRA: - 
Enabled ezsystems/ezplatform-form-builder routes.
> Enabled ezsystems/ezplatform-form-builder routes

- composer.json
- config/bundles.php
- config/routes/ezplatform_calendar.yaml
> JIRA: -
Enabled `ezsystems/ezplatform-calendar`
>  Enabled ezsystems/ezplatform-calendar

- README.md
> JIRA: -
Better late than never :sweat_smile:
> Updated year in README.md

- behat.yml.dist
JIRA: https://jira.ez.no/browse/EZEE-2899
Related PRs:
https://github.com/ezsystems/ezplatform-page-builder/pull/412
https://github.com/ezsystems/ezplatform-admin-ui/pull/1113
https://github.com/ezsystems/ezplatform-workflow/pull/79
Adding workflow Behat suite
> [Behat] Added Workflow config

- composer.json
- config/bundles.php
- config/routes/ezplatform_flex_workflow.yaml
jira: https://jira.ez.no/browse/EZEE-2855
related to :
https://github.com/ezsystems/ezplatform-workflow/pull/82
https://github.com/ezsystems/ezplatform-workflow/pull/81
https://github.com/ezsystems/ezplatform-workflow/pull/80
> EZEE-2907: Removed dependency to flex-workflow

- composer.json
- config/bundles.php
- config/routes/ezplatform_content_comparison.yaml
Enable bundle and add routes to display result of comparison
> EZP-31081: Enable content comparison

- composer.json
- config/bundles.php
- config/routes/ezplatform_content_comparison.yaml
- config/routes/ezplatform_version_comparison.yaml
https://jira.ez.no/browse/EZEE-2995
Bundle PR:
https://github.com/ezsystems/ezplatform-content-comparison/pull/26
> EZEE-2995: Renamed ContentComparison Bundle to Version Comparison

- config/routes/ezplatform_date_based_publisher.yaml
| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZEE-2988 ; https://jira.ez.no/browse/EZEE-2989 ; https://jira.ez.no/browse/EZEE-2990
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)
Scheduling hide content (As an Editor, I want to schedule hiding of a content item) - added new date-based-publisher routing
Related PR:
https://github.com/ezsystems/date-based-publisher/pull/158/files
https://github.com/ezsystems/ezplatform-admin-ui/pull/1280
> EZEE-2988: Content hide schedule - added new DBP routing

- assets/scss/welcome-page.scss
- config/packages/ezplatform_welcome_page.yaml
- templates/themes/standard/full/welcome_page.html.twig
- templates/themes/standard/pagelayout.html.twig
- translations/ezplatform_welcome_page.en.xlf
- webpack.config.js
https://jira.ez.no/browse/EZP-31518
Installer: https://github.com/ezsystems/ezplatform-ee-installer/pull/66
> EZP-31518: Implement welcome page

- config/packages/behat/ezplatform_site_factory.yaml
- config/packages/ezplatform_site_factory.yaml
Added ezplatform_site_factory.yaml to meta-repository with the reference configuration to make easier to start using the Site Factory.
Related PR: https://github.com/ezsystems/ezplatform-site-factory/pull/50
> Added default configuration for a Site Factory

- upgrade/db/mysql/ezplatform-2.5.latest-to-3.0.0.sql
- upgrade/db/postgresql/ezplatform-2.5.latest-to-3.0.0.sql
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-2880](https://jira.ez.no/browse/EZP-2880)
| **Type**                                   | feature
| **Target eZ Platform version** | `v3.0`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
> EZEE-2880: Added support for stage and transition actions

- composer.json
- config/bundles.php
- config/packages/ezplatform_http_cache_fastly.yaml
> JIRA: https://jira.ez.no/browse/EZEE-3079
> Requires: https://github.com/ezsystems/ezplatform-http-cache-fastly/pull/20
> EZEE-3079: Added ezsystems/ezplatform-http-cache-fastly

- upgrade/db/mysql/ezplatform-2.5.latest-to-3.0.0.sql
- upgrade/db/postgresql/ezplatform-2.5.latest-to-3.0.0.sql
JIRA: https://jira.ez.no/browse/EZEE-2988
> EZEE-2988: Provided migration script for scheduled hiding

- config/packages/ezplatform.yaml
> Update cache_pool comment in ezplatform.yaml

- config/packages/ezplatform.yaml
Reverts ezsystems/ezplatform-ee#141
> Revert "Update cache_pool comment in ezplatform.yaml"

- app/config/routing.yml
https://jira.ez.no/browse/EZEE-2497
https://github.com/ezsystems/ezplatform-form-builder/pull/235
> EZEE-2497: Enabled Ajax Captcha routing file

- composer.json
- config/bundles.php
- config/packages/ezplatform_elastic_search_engine.yaml
> JIRA: -
Enabled `ezsystems/ezplatform-elastic-search-engine`
> Enabled ezsystems/ezplatform-elastic-search-engine

- .env
- config/packages/ezplatform_elastic_search_engine.yaml
> JIRA: -
Added ELASTICSEARCH\_DSN env variable to `.env`
> Exposed ELASTICSEARCH_DSN env variable

- composer.json
- config/bundles.php
JIRA: https://jira.ez.no/browse/EZEE-3176
Related to: https://github.com/ezsystems/ezplatform-permissions/pull/1
> EZEE-3176: Enable Permissions bundle

- upgrade/db/mysql/ezplatform-3.1.0-to-3.2.0.sql
- upgrade/db/postgresql/ezplatform-3.1.0-to-3.2.0.sql
Added missing upgrade files to [EZEE-3244:](https://jira.ez.no/browse/EZEE-3244) Added path to site configuration
> Added missing upgrade files

- composer.json
- config/bundles.php
- config/routes/ezplatform_connector_dam.yaml
https://github.com/ezsystems/ezplatform-connector-dam
> Enabled ezsystems/ezplatform-connector-dam

- config/routes/ibexa_platform_connector_dam.yaml
https://github.com/ezsystems/ezplatform-connector-dam/pull/16
> EZP-32004: Added REST routes for DAM Assets

- .platform.app.yaml
- .platform/services.yaml
- config/packages/overrides/platformsh.php
> JIRA: - 
Added configuration template for ElasticSearch. 
_Note for reviewers: please review PR carefully. I'm pretty new to platform.sh ;-)_
*   [x] Confirm that ES 7.7 is available
> [Platform.sh]: ElasticSearch support

- templates/themes/standard/full/welcome_page.html.twig
- translations/ibexa_platform_welcome_page.en.xlf
https://jira.ez.no/browse/EZP-32040
> EZP-32040: Redesigned welcome page

- composer.json
- config/bundles.php
| Question      | Answer
| ------------- | ---
| Tickets       |  [EZP-31309](https://jira.ez.no/browse/EZP-31309) 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [TTL-2.0](https://github.com/ezsystems/ezplatform-connector-dam/blob/master/LICENSE)
Enabled IbexaPlatformMigrationBundle
> Enabled IbexaPlatformMigrationBundle

- composer.json
- config/bundles.php
- config/routes/ibexa_platform_image_editor.yaml
~Waiting for merged https://github.com/ibexa/image-editor/pull/4 for route file.~
> Enabled ImageEditor bundle

- config/packages/overrides/generic.php
- config/packages/overrides/platformsh.php
Yesterday I merged file from OSS which is incorrect for EE. This PR restores correct file.
> Reverted correct platformsh.php config file

- composer.json
- config/bundles.php
- config/packages/knpu_oauth2_client.yaml
- config/packages/security.yaml
- config/routes/ibexa_platform_oauth2_client.yaml
> JIRA: -
Enabled ibexa/oauth-client bundle.
> Enabled ibexa/oauth-client

- upgrade/db/postgresql/ezplatform-3.1.0-to-3.2.0.sql
this sql was added here: https://github.com/ezsystems/ezplatform-ee/pull/155
> Removed incorrect char for postgreSQL
