composer.json
Added captcha library dependency to `composer.json` as required by `ezsystems/ezstudio-form-builder` package.
JIRA: https://jira.ez.no/browse/EZS-1298
=> EZS-1298: Added captcha library to composer.json

.platform.app.yaml, doc/platformsh/INSTALL.md, doc/platformsh/README.md
> https://jira.ez.no/browse/EZS-1402
> Ready for review
Adds the necessary config files to run studio on platform.sh. This should also be added in the ezstudio-demo repo. Clustering not yet covered.
=> EZS-1402: Adjust platform.sh config for eZ Platform Enterprise

behat.yml.dist
Jira: https://jira.ez.no/browse/EZEE-1484
Just adding one line to imports for date based publisher.
Required by https://github.com/ezsystems/date-based-publisher/pull/21.
=> [Behat] EZEE-1484: Add behat suites line for date based publisher

behat.yml.dist
It was by mistake added to ezplatform-ee clean meta repo and should go directly to demo fork.
=> Revert EZEE-1516 Adding of import line for demo bundle

.env, app/AppKernel.php, app/config/default_parameters.yml, app/config/env/generic.php, app/config/ezplatform.yml, composer.json, doc/docker/base-dev.yml, doc/docker/base-prod.yml, doc/docker/my-ez-app-stack.yml
This branch enables ezplatform-http-cache-fastly in ee
This PR should be rebased once https://github.com/ezsystems/ezplatform/pull/231 is merged to ezplatform-ee
=> Enable ezplatform-http-cache-fastly

behat.yml.dist
JIRA: https://jira.ez.no/browse/EZP-28041
Required by: https://github.com/ezsystems/StudioUIBundle/pull/872
Content on the fly does not exist in v2, this file is missing.
Should be merged to ezplatform-ee-demo too.
=> EZP-28041: Remove nonexistent file

app/config/ezplatform.yml
Adding default PageBuilder config, as in demo:
https://github.com/ezsystems/ezplatform-ee-demo/blob/2.2-test/app/config/ezplatform.yml#L78
=> Add default PageBuiler siteacces configuration

app/config/config.yml
> JIRA: https://jira.ez.no/browse/EZP-28890
Added configuration of translations extraction for the page builder. Thanks to this change extracting translations is done via `php bin/console translation:extract -c page_builder`  command.
=> EZP-28890: Added configuration of translations extraction for the page builder

app/AppKernel.php
> JIRA: https://jira.ez.no/browse/EZEE-2557
After fixing how configuration is merged in https://github.com/ezsystems/ezplatform-page-fieldtype/pull/78, Page Builder could not  properly override default settings because it was prepending configuration before `EzPlatformPageFieldTypeBundle`. In order to assure proper behavior it has to be loaded after all other bundles (mainly PB).
=> EZEE-2557: Can't override default block settings

app/AppKernel.php, app/config/config.yml, app/config/security.yml
> JIRA: https://jira.ez.no/browse/EZEE-2572
Enabled `LexikJWTAuthenticationBundle` (required by https://github.com/ezsystems/ezplatform-page-builder/pull/275) and configured "editorial mode" guard.
=> EZEE-2572: Enabled LexikJWTAuthenticationBundle and configurated editorial mode guard

composer.json
> JIRA: https://jira.ez.no/browse/EZP-30217
=> EZP-30217: GraphQL generate schema command fails after composer install due to database not being installed yet

behat.yml.dist
https://github.com/ezsystems/ezplatform-ee/pull/114/files removed the flex-workflow dependency, meaning that Behat no longer can reference that file.
=> [Behat] Removed FlexWf suite

composer.json
Looks like this one was left during conflicts resolve.
=> fix: Removed ezsystems/repository-forms package from composer.json

config/packages/behat/ez_platform_site_factory.yaml, config/packages/behat/ezplatform.yaml
To make testing easier (and avoid wasting time setting up SiteFactory every time we want to check something) this PR adds basic SiteFactory config.
It's based on instructions provided by Mikołaj, it's for `behat` Symfony env only - meaning no changes for prod and dev envs.
In the future we can use it for automation as well. 
Screenshot:
=> Added basic SiteFactory configuration for Behat env

app/config/env/generic.php
Basically, this PR makes it no longer required to set `HTTPCACHE_PURGE_SERVER` if you already have set `HTTPCACHE_PURGE_TYPE=fastly`
=> EZEE-2968: Simply Fastly configuration

config/packages/ezplatform.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZEE-3097
| **Type**                                   | feature
| **Target version**                    | `master`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
| **Related PR**                       | https://github.com/ezsystems/ezplatform-site-factory/pull/59
This PR adds Location ID of Site skeleton for the Content Tree module. This is needed to render a proper tree when a user enters a child location.
=> EZEE-3097: Added content tree root Location ID for Site skeletons

config/packages/ezplatform_site_factory.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | N/A
| **Type**                                   | improvement
| **Target version** | `v1.x`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no
Adjust example's thumbnail size to the various usages for self-documentation.
It seems after few tests than the best image size to use for a Site Factory site template is 160x95 which won't be resized or, worst, streched.
The commented example could recommend this size of 160x95.
**Tests**
Used images
| original size | shorten name | path |
| ------: | :------ | :--- |
| 500x500 | 500/500 | …
=> ezplatform_site_factory.yaml: Adjust example's thumbnail size

upgrade/db/mysql/ezplatform-2.5.latest-to-3.0.0.sql, upgrade/db/postgresql/ezplatform-2.5.latest-to-3.0.0.sql
**JIRA issue**: [EZEE-3214](https://jira.ez.no/browse/EZEE-3214)
**Type**: bug
We still seem to support MySQL 5.7. Unfortunately default values for TEXT columns [are not supported](https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html) in that version.
Seems like [Workflow Gateway sets it by default](https://github.com/ezsystems/ezplatform-workflow/blob/v2.0.1/src/lib/Persistence/Gateway/DoctrineGateway.php#L386) so it's rather required. Current schema seems to [confirm that](https://github.com/ezsystems/ezplatform-workflow/blob/v2.0.1/src/bundle/Resources/config/storage/schema.yaml#L22) as well.
Hence the change.
=> EZEE-3214: Dropped default value from Workflow Markings message column

config/packages/doctrine.yaml
Wrong Doctrine DBAL storage connection is used when a new connection is appended in a 3rd party bundle.
More details at [https://jira.ez.no/browse/EZP-31780](https://jira.ez.no/browse/EZP-31780).
=> EZP-31780: Default doctrine dbal connection issue

app/config/ezplatform_behat.yml
In order to have Behat scenarios working well, we need access to some services which help operate with EE features  (ex. WorkflowFacade for WorklowBundle)   
BehatBundle does not provide EE facades and helpers until there is no indication that it works under EE.
=> EZEE-3155: Enable enterprise services in Behat

composer.json, config/bundles.php, config/routes/ibexa_platform_segmentation.yaml, config/routes/ibexa_segmentation.yaml
> JIRA: https://jira.ez.no/browse/EZEE-3224
=> EZEE-3224: Added ezplatform-segmentation package

behat.yml.dist
| Question      | Answer
| ------------- | ---
| Tickets       |  [EZEE-2817](https://jira.ez.no/browse/EZEE-2817) 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [TTL-2.0](https://github.com/ezsystems/ezplatform-connector-dam/blob/master/LICENSE)
In order to run the new behat's scenarios for ezsystems/ezplatform-page-fieldtype:156, new import is needed in `behat.yml.dist`
=> EZEE-2817: Added behat suite for ezplatform-page-fieldtype

.platform.app.yaml
> JIRA: -
Follow up for #148. 
To avoid  
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"index_template [default] already exists"}],"type":"illegal_argument_exception","reason":"index_template [default] already exists"},"status":400} 
```
errors, create ES mappings only when `ezplatform-install` is executed.
=> [Platform.sh] Avoid recreating ES mappings on each deploy

config/packages/ezplatform_form_builder.yaml, config/packages/ezplatform_page_builder.yaml
This configuration is obsolete. The correct one is in `\EzSystems\EzPlatformFormBuilderBundle\DependencyInjection\EzPlatformFormBuilderExtension::prependJMSTranslation` and `\EzSystems\EzPlatformPageBuilderBundle\DependencyInjection\EzPlatformPageBuilderExtension::prependJMSTranslation`
=> Removed obsolete configuration of translation for page and form builders

composer.json, config/bundles.php, upgrade/db/mysql/ezplatform-3.2.0-to-3.3.0.sql, upgrade/db/postgresql/ezplatform-3.2.0-to-3.3.0.sql
The branch `v3.2-to-v3.3-upgrade` should be merged when doing a version upgrade to make the transition from v3.2 (metarepository installation) to v3.3 (flex project) easier.
It contains:
1) Composer.json from ibexa/website-skeleton (https://github.com/ibexa/website-skeleton/blob/main/composer.json) so that our users don't have to apply the changes manually. *It's modified to use the `update.ibexa.co` server by default, so this step doesn't have to be applied manually*.
2) removal of `EzPlatformEnterpriseEditionInstallerBundle` from bundles - this bundle is not used anymore and needs to be disabled, but it's not unconfigured by Composer during removal
3) Database upgrade scripts for the data present in Experience installer:
https://github.com/ibexa/installer/blob/main/src/bundle/Resources/i …
=> Prepared branch for easier version upgrade

upgrade/db/mysql/ezplatform-3.2.5-to-3.2.6.sql
> JIRA: https://issues.ibexa.co/browse/EZEE-3003
This adds migration script for people upgrading from 3.2.5 to upcoming 3.2.6. Postgres is not affected.
=> EZEE-3003: Increased ezpage_attributes.value size limit

upgrade/db/postgresql/ezplatform-2.5.latest-to-3.0.0.sql
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **Type**                                   | improvement
| **Target Ibexa version** | `v3.2`
| **BC breaks**                          | no
Rebased and fixed version of ezsystems/ezplatform-ee#178. It's safer to have a default value for the new non-nullable column.
See if Workflow can still be saved after executing the upgrade on the older version. Environment: PostgreSQL 10+.
=> Added default value for not nullable column in 3.x upgrade script
